local loxygen = require('src.loxygen')
local tokenizer = require('src.tokenizer').lua
local json = require('src.json')

local lapp = require('pl.lapp')
local file = require('pl.file')

local args = lapp [[
Loxygen - A Lua documentation generator for Lua.

Available options
  --all (default false) Include local items in documentation.
  --boilerplate (default false) Removal of boilerplate / license block comments.
  --box (default false) Include infobox in output.
  --caption (default true) Infobox image caption.
  --card (default true) Include endmatter card in the output at the end of the documentation.
  --code (default false) Only document Docbunto code items while excluding article infobox and lede.
  --colon (default false) Format tags with a : suffix and without the @ prefix.
  --footer (default true) Append a horizontal line & 'generated by Docbunto' to the bottom of the output.
  --image Infobox image.
  --noluaref (default false) Don't link to the Lua reference manual for types.
  --plain (default false) Disable Markdown formatting in documentation.
  --preface Preface text to insert between lede & item documentation, used to provide usage and code examples.
  --simple (default false) Limit documentation to descriptions only. (default false)
  --sort (default false) Sort documentation items in alphabetical order.
  --strip (default false) Remove table index in documentation.
  --verbose (default false) Show the code description of a package function when documenting function modules.
  --ulist (default false) Indent subitems as <ul> lists - LDoc/JSDoc behaviour.
  <method> (string) Command word - either 'dump' or 'generate'.
  <file> (string) Path to the Lua module being documented.
]]

if args.method == 'parse' then
    local taglet = loxygen.taglet(args.file, args)
    print(json.encode(taglet, { indent = '  ' }))
end

if args.method == 'serialise' then
    local documentation = loxygen.build(args.file, args)
    print(documentation)
end

if args.method == 'tokenize' then
    local contents = file.read(args.file)
    local tokens = tokenizer(contents)
    print(json.encode(tokens, { indent = '  ' }))
end